In [5]:
import numpy as np
import open3d as o3d
from open3d_ros_helper import open3d_ros_helper as orh
distance = 290

**Load Pointcloud from file downpcd_pointcloud.pcd**

In [6]:
#o3d.io.write_point_cloud('downpcd_pointcloud.pcd', downpcd, write_ascii=False, compressed=False, print_progress=False)

downpcd = o3d.io.read_point_cloud('downpcd_pointcloud.pcd', format='auto', remove_nan_points=False, remove_infinite_points=False, print_progress=False)
v2_camera = np.array(np.asarray(downpcd.normals))
v2_camera

array([[ 1.18833103e-11, -2.33872574e-11,  1.00000000e+00],
       [-1.75298198e-13, -8.78566837e-12,  1.00000000e+00],
       [-6.74436722e-12, -9.13626466e-12,  1.00000000e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 1.18963243e-13,  2.82913732e-12,  1.00000000e+00],
       [-4.16675781e-13,  8.84612275e-14,  1.00000000e+00]])

In [7]:
rec = np.array(downpcd.points)
rec

array([[ 0.31790507, -0.23892866, -0.46200001],
       [ 0.31190687, -0.23892866, -0.46200001],
       [ 0.31090716, -0.23892866, -0.46200001],
       ...,
       [ 0.01889046, -0.00503746, -0.29100001],
       [-0.29014713,  0.095082  , -0.45300001],
       [ 0.02077951, -0.00503746, -0.29100001]])

In [8]:
idx = np.where(abs(rec[:,2]) < (distance/1000)+0.01)[0] #fetch all indexes of values less than distance of center of img 0.3 in column 3 of rec
idx

array([  1668,   1669,   1670, ..., 169404, 169405, 169407])

In [9]:
zz=downpcd.select_by_index(idx, invert=False)
o3d.visualization.draw_geometries([zz], point_show_normal=True)

nor = np.array(zz.normals)
pts = np.array(zz.points)

In [10]:
idx2 = np.where((abs(pts[:,0]) < 0.0005) & (abs(pts[:,1]) < 0.0001))[0]
idx2

array([54414])

In [11]:
pts[54414]

array([-0.00031376,  0.        , -0.28999999])

In [12]:
np.min(abs(pts[:,0]))

0.0003105133364442736

**Applying a Filter on a 3D array**

In [13]:
x_range = [-0.001,(np.min(abs(pts[:,0]))+0.0001)]
y_range = [np.min(abs(pts[:,1])), np.min(abs(pts[:,1]))]
z_range = [-(distance/1000)-0.01,(distance/1000)+0.01]

za = orh.apply_pass_through_filter(zz, x_range, y_range, z_range)
za

PointCloud with 1 points.

In [14]:
zaza = np.array(za.points)
zaza

array([[-0.00031376,  0.        , -0.28999999]])

In [15]:
np.min(abs(zaza[:,0]))

0.00031375911203213036