In [1]:
import numpy as np

In [119]:
x = np.array([[20, 30, 10],[10,20,30],[0,30,20],[90,60,10]])
x


array([[20, 30, 10],
       [10, 20, 30],
       [ 0, 30, 20],
       [90, 60, 10]])

In [148]:
y = np.array([[100, 200, 300],[400,500,600],[700,800,900],[1000,1100,1200]])
y

array([[ 100,  200,  300],
       [ 400,  500,  600],
       [ 700,  800,  900],
       [1000, 1100, 1200]])

In [149]:
ind = np.argsort(x[:, 0]) #Sort based on first column
sorted_x = x[ind]
sorted_x

array([[ 0, 30, 20],
       [10, 20, 30],
       [20, 30, 10],
       [90, 60, 10]])

In [150]:
sorted_y = y[ind] #Y is rearranged Based on x's index
sorted_y

array([[ 700,  800,  900],
       [ 400,  500,  600],
       [ 100,  200,  300],
       [1000, 1100, 1200]])